import type { AcademicCourse, Differentiator, Project, ProofPoint, SkillCategory } from './types';

export const SKILL_CATEGORIES: SkillCategory[] = [
  {
    id: 'llm',
    label: 'LLM Engineering',
    icon: '⬡',
    color: '#38bdf8',
    glow: 'rgba(56,189,248,0.18)',
    skills: [
      { name: 'RAG Architecture', level: 95, proof: 'UMD Chatbot · Multiagent RAG · Marketing Tool' },
      { name: 'LangChain / LangGraph', level: 90, proof: 'Event Scheduler AI · Multiagent RAG-Chatbot' },
      { name: 'OpenAI API', level: 95, proof: 'Marketing Intelligence Platform · Portfolio Chatbot' },
      { name: 'Google Gemini', level: 88, proof: 'Social Media Bot · Event Scheduler AI' },
      { name: 'ReACT Agents', level: 85, proof: 'Multiagent RAG-Chatbot · LangGraph pipelines' },
      { name: 'Prompt Engineering', level: 90, proof: 'Marketing Tool — structured output normalization' },
      { name: 'Vector Memory Systems', level: 88, proof: 'Marketing Tool — top-k retrieval injection, chunking' },
      { name: 'Multi-Agent Orchestration', level: 85, proof: '8-service agent pipeline · Lead qualification agents' },
    ],
  },
  {
    id: 'genai',
    label: 'Generative AI',
    icon: '◈',
    color: '#a78bfa',
    glow: 'rgba(167,139,250,0.18)',
    skills: [
      { name: 'AI Content Generation', level: 92, proof: 'Social Media Bot — 30+ platform variations' },
      { name: 'Conversational AI', level: 90, proof: 'UMD RAG Chatbot · Marketing Discovery Interview' },
      { name: 'Embeddings & Semantic Search', level: 88, proof: 'Chroma · sentence-transformers · OpenAI embeddings' },
      { name: 'Vector Databases', level: 87, proof: 'Chroma · Qdrant research · FAISS' },
      { name: 'Structured Output Normalization', level: 85, proof: 'Marketing Tool — JSON/non-JSON defensive parsing' },
      { name: 'AI UX Design', level: 88, proof: 'Live conversation analysis panel · explainability UI' },
      { name: 'A/B Testing Agents', level: 78, proof: 'Graduate Research — AI-powered A/B optimization' },
      { name: 'Token Optimization', level: 85, proof: 'Marketing Tool — 40% prompt token reduction' },
    ],
  },
  {
    id: 'mlops',
    label: 'MLOps & Production',
    icon: '⬟',
    color: '#34d399',
    glow: 'rgba(52,211,153,0.18)',
    skills: [
      { name: 'Docker & Containerization', level: 88, proof: 'Marketing Tool — Docker Compose production setup' },
      { name: 'CI/CD Pipelines', level: 85, proof: 'TCS — Jenkins, GitLab · GitHub Actions' },
      { name: 'AWS Cloud (EC2, RDS, S3)', level: 82, proof: 'Event Scheduler AI — Elastic Beanstalk deployment' },
      { name: 'FastAPI', level: 92, proof: 'Marketing Tool · Multiagent RAG-Chatbot backend' },
      { name: 'PostgreSQL + Alembic', level: 88, proof: 'Marketing Tool — migration-first schema discipline' },
      { name: 'RESTful API Design', level: 90, proof: 'TCS — Spring Boot · FastAPI · Node.js' },
      { name: 'Agile / Scrum', level: 90, proof: 'TCS (3.5 yrs) · UMD weekly stakeholder syncs' },
      { name: 'System Design', level: 85, proof: 'RAG chatbot architecture docs · SOW · Design Reports' },
    ],
  },
  {
    id: 'ml',
    label: 'ML & Data Science',
    icon: '◇',
    color: '#f59e0b',
    glow: 'rgba(245,158,11,0.18)',
    skills: [
      { name: 'XGBoost / LightGBM', level: 85, proof: 'E-Livestock predictive disease model' },
      { name: 'Scikit-Learn', level: 88, proof: 'Sparks Foundation — classification & regression' },
      { name: 'Feature Engineering', level: 85, proof: 'Sparks Foundation — 85% prediction accuracy' },
      { name: 'ELT Pipelines', level: 83, proof: 'E-Livestock — analytics-ready data pipeline' },
      { name: 'Data Visualization', level: 85, proof: 'E-Livestock dashboard (Chart.js) · Tableau (Blitz Jobs)' },
      { name: 'SQL & Database Design', level: 88, proof: 'Hotel Feedback ERD · TCS BNY Mellon · PostgreSQL' },
      { name: 'Pandas / NumPy', level: 87, proof: 'Sparks Foundation · COVID-19 analysis · Hotel project' },
      { name: 'R (Statistical Modeling)', level: 80, proof: 'YouTube predictive model — 77% accuracy (100k rows)' },
    ],
  },
  {
    id: 'fullstack',
    label: 'Full-Stack AI Apps',
    icon: '⬡',
    color: '#f472b6',
    glow: 'rgba(244,114,182,0.18)',
    skills: [
      { name: 'React / Next.js', level: 92, proof: 'Portfolio · Marketing Tool · Multiagent Chatbot' },
      { name: 'Python / Flask / FastAPI', level: 93, proof: 'All AI projects — primary backend language' },
      { name: 'Node.js / TypeScript', level: 85, proof: 'TCS (3.5 yrs) · Portfolio website backend' },
      { name: 'Authentication Systems', level: 88, proof: 'JWT auth · Google OAuth 2.0 · protected routes' },
      { name: 'MCP Server Integration', level: 82, proof: 'Event Scheduler AI — Google Calendar MCP' },
      { name: 'MySQL / PostgreSQL', level: 88, proof: 'Event Scheduler AI · Marketing Tool · Portfolio' },
      { name: 'Google Maps API', level: 80, proof: 'Best for DMV — interactive ecosystem mapping' },
      { name: 'Figma / UI Design', level: 78, proof: 'UMD Chatbot — UI layout design in Figma' },
    ],
  },
  {
    id: 'academic',
    label: 'Academic Foundation',
    icon: '🎓',
    color: '#e879f9',
    glow: 'rgba(232,121,249,0.18)',
    skills: [],
  },
];

export const ACADEMIC_COURSES: AcademicCourse[] = [
  {
    code: 'BUDT758O',
    name: 'Designing AI Systems',
    institution: 'UMD · Robert H. Smith School of Business',
    grade: '4.0 / 4.0',
    color: '#38bdf8',
    icon: '⬡',
    summary: 'End-to-end AI system architecture — from RAG pipelines to agentic workflows and production LLM deployment.',
    topics: [
      'Retrieval-Augmented Generation (RAG)',
      'LangChain & LangGraph',
      'Agentic Systems & ReACT',
      'Advanced Prompt Engineering',
      'HyDE & RAG Fusion',
      'Fine-Tuning LLMs',
      'Vector Databases & Embeddings',
      'Model Distillation',
      'AI Ethics & Responsible AI',
      'Transformer Architecture',
    ],
    applied: [
      { project: 'Multiagent RAG-Chatbot', detail: 'LangGraph stateful agents + ReACT loop' },
      { project: 'Marketing Intelligence Platform', detail: '8-service agent pipeline + vector memory' },
      { project: 'UMD AI Chatbot System', detail: 'RAG architecture + policy summarization' },
    ],
  },
  {
    code: 'BUDT751',
    name: 'Harnessing AI for Business',
    institution: 'UMD · Robert H. Smith School of Business',
    grade: '4.0 / 4.0',
    color: '#a78bfa',
    icon: '◈',
    summary: 'Bridging AI capabilities with business strategy — GenAI product design, deep learning architectures, and agentic AI for enterprise.',
    topics: [
      'Artificial Neural Networks (ANN)',
      'Convolutional Neural Networks (CNN)',
      'Graph Neural Networks (GNN)',
      'Generative AI & OpenAI APIs',
      'AI Strategy & Business Alignment',
      'Adversarial Networks (GANs)',
      'AI Ethics & Moral Dilemmas',
      'Agentic AI Workflows',
      'New Product Development with AI',
      'AI Impact on Industries',
    ],
    applied: [
      { project: 'E-Livestock Dashboard', detail: 'ML predictive models + AI insight summaries' },
      { project: 'Graduate Research — Teaching Tool', detail: 'AI-guided lead qualification + content agents' },
      { project: 'Marketing Intelligence Platform', detail: 'AI strategy → product execution pipeline' },
    ],
  },
  {
    code: 'BUDT704',
    name: 'Data Processing & Analysis in Python',
    institution: 'UMD · Robert H. Smith School of Business',
    grade: '4.0 / 4.0',
    color: '#34d399',
    icon: '⬟',
    summary: 'Python-first data science — NumPy/Pandas to NLP, Word2Vec embeddings, and deep learning with PyTorch and Keras.',
    topics: [
      'Python Programming (Advanced)',
      'Pandas & NumPy',
      'Regular Expressions & Text Cleaning',
      'NLP & Text Mining',
      'Word2Vec Embeddings',
      'TF-IDF & Bag of Words',
      'Deep Learning Foundations',
      'PyTorch & Keras',
      'CNNs (MNIST digit recognition)',
      'Backpropagation & Optimization',
    ],
    applied: [
      { project: 'AI Social Media Bot', detail: 'NLP-based prompt optimization per platform' },
      { project: 'Sparks Foundation Internship', detail: 'scikit-learn pipelines · 85% accuracy' },
      { project: 'COVID-19 Analysis', detail: 'Pandas + NumPy for 100K+ record analysis' },
    ],
  },
  {
    code: 'BUDT733',
    name: 'Data Mining & Predictive Analytics',
    institution: 'UMD · Robert H. Smith School of Business',
    grade: '4.0 / 4.0',
    color: '#f59e0b',
    icon: '◇',
    summary: 'Full ML workflow from raw data to production predictions — classification, regression, ensemble methods on real business datasets.',
    topics: [
      'Supervised Learning (Classification & Regression)',
      'Logistic Regression',
      'Nonlinear Modeling',
      'Cross-Validation',
      'Feature Engineering & Selection',
      'Model Evaluation Metrics',
      'Complexity Control & Regularization',
      'Ensemble Methods',
      'R Programming (Tidyverse)',
      'Predictive Pipeline Design',
    ],
    applied: [
      { project: 'E-Livestock Dashboard', detail: 'XGBoost + LightGBM predictive disease model' },
      { project: 'YouTube Success Prediction', detail: '77% accuracy on 100K-row dataset in R' },
      { project: 'Blitz Jobs Internship', detail: 'ML algorithm design for marketing targeting' },
    ],
  },
  {
    code: 'BUDT737',
    name: 'Enterprise Cloud & Big Data',
    institution: 'UMD · Robert H. Smith School of Business',
    grade: '3.7 / 4.0',
    color: '#f472b6',
    icon: '✦',
    summary: 'Cloud-native big data engineering — Spark, Kafka, NoSQL databases, and ML pipelines on GCP and distributed systems.',
    topics: [
      'Google Cloud Platform (GCP)',
      'Apache Spark (PySpark, RDDs, DataFrames)',
      'Apache Kafka (Real-time Streaming)',
      'Hadoop / MapReduce / HDFS',
      'MongoDB (Document Database)',
      'Neo4j (Graph Database)',
      'Cassandra & HBase',
      'Spark SQL & GraphFrames',
      'ML Pipelines at Scale',
      'Hyperparameter Tuning on Distributed Systems',
    ],
    applied: [
      { project: 'Event Scheduler AI', detail: 'AWS EC2, RDS, S3, Elastic Beanstalk deployment' },
      { project: 'E-Livestock Pipeline', detail: 'ELT pipeline design + multi-source data coordination' },
      { project: 'Marketing Tool', detail: 'PostgreSQL schema + scalable API architecture' },
    ],
  },
];

export const PROJECTS: Project[] = [
  {
    name: 'AI-Driven Marketing Intelligence Platform',
    role: 'Solo Builder',
    tags: ['FastAPI', 'OpenAI', 'LangChain', 'PostgreSQL', 'Docker', 'RAG'],
    color: '#38bdf8',
    highlight: '8-service modular agent pipeline · 40% token reduction · reliability engineering',
    skills: ['llm', 'genai', 'mlops', 'fullstack'],
    impactMetrics: ['8 services', '40% token reduction', 'Production-ready'],
    problem: 'Marketing teams needed reliable AI outputs without high token waste and brittle prompt behavior.',
    architecture: 'FastAPI microservices + retrieval context layer + PostgreSQL + Dockerized service boundaries.',
    tradeoffs: 'Accepted added orchestration complexity to gain observability and deterministic fallback behavior.',
  },
  {
    name: 'Document Analysis Multiagent RAG-Chatbot',
    role: 'Solo Builder',
    tags: ['LangGraph', 'Gemini', 'ReACT', 'Chroma', 'FastAPI', 'Next.js'],
    color: '#a78bfa',
    highlight: 'ReACT agents · VLM embeddings · persistent memory · multi-source ingestion',
    skills: ['llm', 'genai', 'fullstack'],
    impactMetrics: ['Multi-agent flow', 'Persistent memory', 'RAG retrieval'],
    problem: 'Users needed high-accuracy answers over uploaded documents with better context retention.',
    architecture: 'LangGraph ReACT agents + vector retrieval + persistent memory + Next.js frontend.',
    tradeoffs: 'Chose higher latency from deeper orchestration to improve answer quality and traceability.',
  },
  {
    name: 'AI-Powered Portfolio Website',
    role: 'Solo Builder',
    tags: ['Next.js 15', 'Gemini', 'RAG', 'PostgreSQL', 'TypeScript', 'Vercel'],
    color: '#e879f9',
    highlight: 'RAG chatbot · live AI news digest · ISR edge caching · <24 Gemini calls/day',
    skills: ['llm', 'genai', 'fullstack'],
    impactMetrics: ['RAG chatbot', 'Hourly AI digest', '<30ms edge response'],
    problem: 'A static resume page cannot demonstrate production AI engineering — needed a live system that proves end-to-end AI delivery.',
    architecture: 'Next.js 15 App Router server components + Gemini embeddings + pgvector RAG + ISR hourly revalidation for AI news feed.',
    tradeoffs: 'Chose ISR over on-demand rendering to cap Gemini costs at ≤24 calls/day while still serving fresh content to all visitors.',
  },
  {
    name: 'AI Chatbot System — UMD Smith School',
    role: 'AI Chatbot System Developer',
    tags: ['RAG', 'Flask', 'React', 'OpenAI', 'Anthropic', 'sentence-transformers'],
    color: '#34d399',
    highlight: 'Stakeholder-driven RAG system · admin document management · policy summarization',
    skills: ['llm', 'genai', 'fullstack'],
    impactMetrics: ['Stakeholder-aligned', 'RAG architecture', 'Admin controls'],
    problem: 'School stakeholders needed searchable policy/document support without manual triage overhead.',
    architecture: 'RAG chatbot service with document management controls and guided frontend workflows.',
    tradeoffs: 'Prioritized explainability and governance features over aggressive latency optimization.',
  },
  {
    name: 'Event Scheduler AI',
    role: 'Solo Builder',
    tags: ['LangChain', 'Gemini', 'MCP', 'AWS', 'Flask', 'React', 'MySQL'],
    color: '#f59e0b',
    highlight: 'AI scheduling agent · Google Calendar MCP · real-time availability calculation',
    skills: ['llm', 'mlops', 'fullstack'],
    impactMetrics: ['MCP integration', 'Real-time scheduling', 'Cloud deployment'],
    problem: 'Manual scheduling was slow and error-prone when balancing constraints across participants.',
    architecture: 'LLM agent + Google Calendar MCP + Flask/React + AWS deployment layer.',
    tradeoffs: 'Maintained stricter validation and retries to reduce failed bookings at the cost of complexity.',
  },
  {
    name: 'E-Livestock Analytical Dashboard',
    role: 'Team Lead (5 members)',
    tags: ['XGBoost', 'LightGBM', 'ELT', 'Chart.js', 'React'],
    color: '#f472b6',
    highlight: 'Predictive disease model · ELT pipeline · CEO stakeholder delivery',
    skills: ['ml', 'fullstack'],
    impactMetrics: ['Team lead (5)', 'Predictive model', 'Executive dashboard'],
    problem: 'Stakeholders needed farm-health insights tied to operational decisions, not raw model outputs.',
    architecture: 'ELT pipeline + predictive modeling + React/Chart dashboard for decision-ready analytics.',
    tradeoffs: 'Chose simpler, explainable model outputs for adoption over maximum model sophistication.',
  },
  {
    name: 'AI Social Media Automation Bot',
    role: 'Solo Builder',
    tags: ['Gemini', 'Python', 'APScheduler', 'Twitter API', 'Reddit API'],
    color: '#38bdf8',
    highlight: '30+ content variations · multi-platform AI generation · cron scheduling',
    skills: ['genai', 'fullstack'],
    impactMetrics: ['30+ variations', 'Multi-platform', 'Automated scheduling'],
    problem: 'Content publishing was repetitive and inconsistent across social channels.',
    architecture: 'Python automation + API integrations + scheduled AI content generation workflows.',
    tradeoffs: 'Kept platform-specific templates to improve reliability rather than one-size-fits-all generation.',
  },
];

export const PROOF_POINTS: ProofPoint[] = [
  { stat: '8', label: 'AI Agents Built', sub: 'modular service pipeline' },
  { stat: '40%', label: 'Token Reduction', sub: 'via memory optimization' },
  { stat: '85%', label: 'ML Accuracy', sub: 'Sparks Foundation models' },
  { stat: '7+', label: 'AI Projects', sub: 'shipped to production' },
  { stat: '3', label: 'RAG Systems', sub: 'with vector retrieval' },
  { stat: '7+', label: 'Team Members', sub: 'led as technical lead' },
];

export const DIFFERENTIATORS: Differentiator[] = [
  { icon: '⬡', color: '#38bdf8', title: 'Production over Prototypes', body: 'Every project is deployed with auth, error handling, fallback logic, and migration discipline — not a Jupyter notebook.' },
  { icon: '◈', color: '#a78bfa', title: 'Full-Stack AI Engineering', body: "I build the model layer AND the product layer — FastAPI, React, PostgreSQL, Docker. Most ML engineers can't do both." },
  { icon: '⬟', color: '#34d399', title: 'Stakeholder-Driven Delivery', body: 'Led teams of 7–8 at UMD and TCS. I translate complex AI into business language — a skill explicitly tested at every M7 company.' },
  { icon: '📚', color: '#e879f9', title: 'Rigorous Academic Grounding', body: '3.94 GPA at UMD Smith School. Every theory — RAG, agents, deep learning, big data — was applied directly in shipped production systems.' },
];
